# Generated by Django 5.1.4 on 2025-05-13 22:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarteiraRecomendada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        default="Carteira Recomendada", max_length=255, unique=True
                    ),
                ),
                ("data_criacao", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("setor", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarteiraUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("data_criacao", models.DateField(auto_now_add=True)),
                (
                    "recomendada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallets.carteirarecomendada",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carteiras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Papel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("ticker", models.CharField(max_length=15, unique=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papeis",
                        to="wallets.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("COMPRA", "Compra"), ("VENDA", "Venda")], max_length=6
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_unitario", models.FloatField()),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                ("reinvestido", models.BooleanField(default=False)),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="wallets.carteirausuario",
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallets.papel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PapelCarteiraRecomendada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.carteirarecomendada",
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallets.papel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carteirarecomendada",
            name="papeis",
            field=models.ManyToManyField(
                through="wallets.PapelCarteiraRecomendada", to="wallets.papel"
            ),
        ),
        migrations.CreateModel(
            name="PapelCarteiraUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "carteira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.carteirausuario",
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallets.papel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "preco_fechamento",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("volume", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotacoes",
                        to="wallets.papel",
                    ),
                ),
            ],
            options={
                "unique_together": {("papel", "data")},
            },
        ),
        migrations.CreateModel(
            name="DadoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.contafinanceira",
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados_financeiros",
                        to="wallets.papel",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallets.periodo",
                    ),
                ),
            ],
            options={
                "unique_together": {("papel", "conta", "periodo")},
            },
        ),
    ]
