# Generated by Django 5.1.4 on 2025-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carteirarecomendada",
            name="papeis",
        ),
        migrations.AlterField(
            model_name="carteirarecomendada",
            name="nome",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
