# Generated by Django 5.1.4 on 2025-04-28 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="dadofinanceiro",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nome",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dadofinanceiro",
            name="data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dados_financeiros",
                to="wallets.dataregistro",
            ),
        ),
    ]
