# Generated by Django 5.1.4 on 2025-05-16 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_remove_carteirarecomendada_papeis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movimentacao",
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
            },
        ),
        migrations.RenameField(
            model_name="cotacao",
            old_name="volume",
            new_name="numero_total_acoes",
        ),
        migrations.AddField(
            model_name="cotacao",
            name="preco_abertura",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="preco_unitario",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="papelcarteirarecomendada",
            name="carteira",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papeis",
                to="wallets.carteirarecomendada",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carteirausuario",
            unique_together={("usuario", "nome")},
        ),
        migrations.AlterUniqueTogether(
            name="papelcarteirarecomendada",
            unique_together={("carteira", "papel")},
        ),
        migrations.AlterUniqueTogether(
            name="papelcarteirausuario",
            unique_together={("carteira", "papel")},
        ),
    ]
