# Generated by Django 5.1.4 on 2025-05-18 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_alter_movimentacao_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cotacao",
            old_name="numero_total_acoes",
            new_name="volume",
        ),
        migrations.RemoveField(
            model_name="carteirausuario",
            name="recomendada",
        ),
        migrations.AlterField(
            model_name="papelcarteirarecomendada",
            name="quantidade",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="papelcarteirausuario",
            name="carteira",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papeis",
                to="wallets.carteirausuario",
            ),
        ),
    ]
