# Generated by Django 5.1.4 on 2025-05-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_rename_numero_total_acoes_cotacao_volume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotacao",
            name="numero_total_acoes",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
