# Generated by Django 5.1.4 on 2025-05-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_cotacao_numero_total_acoes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimentacao",
            name="carteira",
        ),
        migrations.RemoveField(
            model_name="movimentacao",
            name="reinvestido",
        ),
        migrations.AddField(
            model_name="carteirausuario",
            name="saldo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="carteira_recomendada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentacoes",
                to="wallets.carteirarecomendada",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="carteira_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentacoes",
                to="wallets.carteirausuario",
            ),
        ),
    ]
