# Generated by Django 5.1.4 on 2025-05-20 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0006_remove_movimentacao_carteira_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotacao",
            name="numero_total_acoes",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotacao",
            name="papel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cotacoes",
                to="wallets.papel",
            ),
        ),
        migrations.AlterField(
            model_name="cotacao",
            name="preco_abertura",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotacao",
            name="preco_fechamento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotacao",
            name="volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
