services:
    db:
        image: postgres:16
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"

    web:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - ./media:/app/media
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - .env
        restart: always

volumes:
    postgres_data:
